<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>md</string>
		<string>mwiki</string>
		<string>mdwiki</string>
	</array>
	<key>name</key>
	<string>MarkdownWiki</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\[\[</string>
			<key>comment</key>
			<string>Match WikiWords and make them into links.</string>
			<key>end</key>
			<string>\]\]</string>
			<key>name</key>
			<string>markup.bold.link.internal.html.markdown.markdownwiki</string>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.content.markdownwiki</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.markdown</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.markdown.markdownwiki</string>
	<key>uuid</key>
	<string>fa1aa050-694b-4177-ba61-92c7c12e9aeb</string>
</dict>
</plist>
